optimizer:
  name: adam
  lr: 1.0e-3
  weight_decay: 0

train:
  epoch: 30
  batch_size: 2000
  save_model: false
  loss: pairwise # bpr
  test_step: 1 # evaluate per {test_step} epochs
  #pretrain_path: ./checkpoint/xxxx.pth
  reproducible: true
  seed: 2023
  tensorboard: true

test:
  metrics: [recall, ndcg] # choose in {ndcg, recall, precision, mrr}
  k: [10, 20, 40] # top-k
  batch_size: 512 # How many users per batch during validation

data:
  type: social
  name: yelp

model:
  name: idea_mhcn_v3 
  layer_num: 2
  reg_weight: 1.0e-3
  embedding_size: 64
  ss_rate: 1.0e-2
  cl_weight: 1.0e-2
  zeta: 0.3
  temperature: 0.1
  sampling_ratio: 0.5
  k: 1

tune:
  enable: true 
  hyperparameters: [layer_num, reg_weight, cl_weight, temperature, sampling_ratio, k] 
  layer_num: [1, 2, 3] 
  reg_weight: [1.0e-1, 1.0e-2, 1.0e-3]
  cl_weight: [1.0, 1.0e-1, 1.0e-2, 1.0e-3]
  temperature: [0.1, 0.2, 0.3, 0.4, 0.5]
  sampling_ratio: [0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
  k: [0.1, 0.5, 1, 5, 10]
